[package]
name = "papers"
version.workspace = true
edition.workspace = true

[dependencies]
papers-openalex = { path = "../papers-openalex" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
wiremock.workspace = true
